"""Local, per-prediction explanations using LightGBM native TreeSHAP values."""

import logging
from collections import defaultdict
from typing import Any

import numpy as np
import pandas as pd

from api.schemas import ExplanationFactor, PredictionExplanation

logger = logging.getLogger(__name__)

EXPLANATION_LABEL = "Model factors influencing this prediction"
EXPLANATION_LIMITATION = (
    "Directions describe this model output, not causes. Relative magnitudes are "
    "scaled against the strongest displayed factor and are not percentages."
)
FALLBACK_MESSAGE = (
    "A local model explanation is temporarily unavailable. The prediction itself "
    "was still generated by the saved model."
)

READABLE_FEATURE_NAMES = {
    "age": "Age",
    "daily_screen_time_hours": "Daily screen time",
    "social_media_hours": "Social media use",
    "gaming_hours": "Gaming time",
    "work_study_hours": "Work or study time",
    "sleep_hours": "Sleep duration",
    "notifications_per_day": "Notifications per day",
    "app_opens_per_day": "App opens per day",
    "weekend_screen_time": "Weekend screen time",
    "gender": "Gender",
    "stress_level": "Stress level",
    "academic_work_impact": "Academic or work impact",
    "social_media_ratio": "Social media share of screen time",
    "gaming_ratio": "Gaming share of screen time",
    "notifications_per_screen_hour": "Notifications per screen hour",
    "sleep_deficit_from_8h": "Difference from eight hours of sleep",
}


def generate_local_explanation(
    pipeline: Any,
    engineered_frame: pd.DataFrame,
    maximum_factors: int = 5,
) -> PredictionExplanation:
    """Explain one transformed row without changing or re-running its prediction.

    LightGBM's native ``pred_contrib`` mode returns TreeSHAP contributions in
    raw-score space plus a final expected-value column. One-hot contributions
    belonging to the same raw categorical field are summed and labelled with
    the input category before ranking.
    """
    try:
        preprocessor = pipeline.named_steps["preprocessor"]
        estimator = pipeline.named_steps["model"]
        transformed = preprocessor.transform(engineered_frame)
        transformed_names = preprocessor.get_feature_names_out().tolist()
        contribution_output = estimator.booster_.predict(
            transformed,
            pred_contrib=True,
        )
        contributions = np.asarray(contribution_output, dtype=float)
        expected_shape = (1, len(transformed_names) + 1)
        if contributions.shape != expected_shape:
            raise ValueError("Unexpected LightGBM contribution shape")
        feature_contributions = contributions[0, :-1]
        if not np.isfinite(feature_contributions).all():
            raise ValueError("Non-finite LightGBM contribution")

        grouped_values: defaultdict[str, float] = defaultdict(float)
        grouped_labels: dict[str, str] = {}
        categorical_columns = _categorical_columns(preprocessor)
        for transformed_name, contribution in zip(
            transformed_names,
            feature_contributions,
            strict=True,
        ):
            source_name, readable_name = _readable_transformed_feature(
                transformed_name,
                engineered_frame,
                categorical_columns,
            )
            grouped_values[source_name] += float(contribution)
            grouped_labels[source_name] = readable_name

        ranked = sorted(
            grouped_values.items(),
            key=lambda item: abs(item[1]),
            reverse=True,
        )
        ranked = [item for item in ranked if abs(item[1]) > 0.0][:maximum_factors]
        if not ranked:
            raise ValueError("No non-zero local contributions")

        strongest = max(abs(value) for _, value in ranked)
        factors = [
            ExplanationFactor(
                feature=grouped_labels[source_name],
                direction=(
                    "increases_predicted_risk"
                    if contribution > 0
                    else "decreases_predicted_risk"
                ),
                display_magnitude=round(abs(contribution) / strongest * 100.0, 1),
            )
            for source_name, contribution in ranked
        ]
        return PredictionExplanation(
            status="available",
            label=EXPLANATION_LABEL,
            method="LightGBM native TreeSHAP contributions",
            factors=factors,
            limitation=EXPLANATION_LIMITATION,
            message=None,
        )
    except Exception as exc:
        logger.warning(
            "Local model explanation unavailable: %s",
            type(exc).__name__,
        )
        return PredictionExplanation(
            status="unavailable",
            label=EXPLANATION_LABEL,
            method=None,
            factors=[],
            limitation=EXPLANATION_LIMITATION,
            message=FALLBACK_MESSAGE,
        )


def _categorical_columns(preprocessor: Any) -> list[str]:
    """Return fitted categorical source columns from the ColumnTransformer."""
    for name, _transformer, columns in preprocessor.transformers_:
        if name == "categorical":
            return list(columns)
    return []


def _readable_transformed_feature(
    transformed_name: str,
    engineered_frame: pd.DataFrame,
    categorical_columns: list[str],
) -> tuple[str, str]:
    """Map a transformed numeric or one-hot name to one readable source field."""
    if transformed_name.startswith("numeric__"):
        source_name = transformed_name.removeprefix("numeric__")
        return source_name, READABLE_FEATURE_NAMES.get(
            source_name,
            _humanize(source_name),
        )

    if transformed_name.startswith("categorical__"):
        encoded_name = transformed_name.removeprefix("categorical__")
        for source_name in sorted(categorical_columns, key=len, reverse=True):
            if encoded_name.startswith(f"{source_name}_"):
                input_value = engineered_frame.iloc[0][source_name]
                base_label = READABLE_FEATURE_NAMES.get(
                    source_name,
                    _humanize(source_name),
                )
                return source_name, f"{base_label}: {input_value}"

    raise ValueError("Unrecognized transformed feature name")


def _humanize(name: str) -> str:
    return name.replace("_", " ").capitalize()
