"""Training-compatible prediction orchestration."""

from typing import Any

import numpy as np
import pandas as pd

from api.explainer import generate_local_explanation
from api.model_loader import ModelService
from api.schemas import PredictionRequest, PredictionResponse
from src.feature_engineering import add_domain_features

DISCLAIMER = (
    "This result is generated by an educational machine-learning model and is "
    "not a medical or psychological diagnosis."
)

RISK_MESSAGES = {
    "Low": (
        "The model detected a low predicted likelihood based on the supplied "
        "usage pattern."
    ),
    "Moderate": (
        "The model detected a moderate predicted likelihood based on the supplied "
        "usage pattern."
    ),
    "High": (
        "The model detected a high predicted likelihood based on the supplied "
        "usage pattern."
    ),
}


def risk_level_for_probability(probability: float) -> str:
    """Map a probability to the configured non-clinical display threshold."""
    if probability < 0.35:
        return "Low"
    if probability < 0.65:
        return "Moderate"
    return "High"


def predict_addiction(
    request: PredictionRequest,
    service: ModelService,
) -> PredictionResponse:
    """Validate, engineer, order, and predict one smartphone-usage record."""
    if service.model is None:
        raise RuntimeError("Model service is unavailable")

    raw_frame = pd.DataFrame([request.model_dump()])
    engineered_frame = add_domain_features(raw_frame)
    expected_features = list(service.metadata["feature_columns"])
    if engineered_frame.columns.tolist() != expected_features:
        raise RuntimeError("Engineered input does not match the saved model schema")

    probabilities = np.asarray(
        service.model.predict_proba(engineered_frame),
        dtype=float,
    )
    classes = np.asarray(service.model.classes_)
    if probabilities.shape != (1, len(classes)) or len(classes) != 2:
        raise RuntimeError("The model returned an invalid probability shape")
    if not np.isfinite(probabilities).all():
        raise RuntimeError("The model returned a non-finite probability")
    if np.any(probabilities < 0.0) or np.any(probabilities > 1.0):
        raise RuntimeError("The model returned a probability outside [0, 1]")

    positive_class: Any = service.schema["target"]["positive_class"]
    positive_indices = np.flatnonzero(classes == positive_class)
    if len(positive_indices) != 1:
        raise RuntimeError("The positive model class is unavailable")

    positive_index = int(positive_indices[0])
    addiction_probability = float(probabilities[0, positive_index])
    non_addiction_probability = float(probabilities[0, 1 - positive_index])
    predicted_class = classes[int(np.argmax(probabilities[0]))]
    if hasattr(predicted_class, "item"):
        predicted_class = predicted_class.item()

    risk_level = risk_level_for_probability(addiction_probability)
    explanation = generate_local_explanation(service.model, engineered_frame)
    return PredictionResponse(
        predicted_class=int(predicted_class),
        addiction_probability=addiction_probability,
        non_addiction_probability=non_addiction_probability,
        risk_level=risk_level,
        risk_message=RISK_MESSAGES[risk_level],
        model_version=service.metadata.get("model_version"),
        disclaimer=DISCLAIMER,
        explanation=explanation,
    )
